object Versions {
    const val coreKtxVersion = "1.8.0"
    const val appCompatVersion = "1.4.2"
    const val materialVersion = "1.6.1"
    const val constraintLayoutVersion = "2.1.4"
    const val hiltAndroidVersion = "2.42"
    const val hiltCompiler = "1.0.0"
    const val workManager = "2.7.1"
    const val retrofitVersion = "2.9.0"
    const val retrofitGsonConverterVersion = "2.9.0"
    const val okHttpInterceptorVersion = "4.9.3"
    const val lifecycleViewModelVersion = "2.5.0"
    const val lifecycleLivedataVersion = "2.5.0"
    const val lifecycleRuntimeVersion = "2.5.0"
    const val coroutinesVersion = "1.6.1"
    const val navigationFragmentVersion = "2.5.0"
    const val navigationUiVersion = "2.5.0"
    const val navigationSafeArgsVersion = "2.5.0"
    const val glideVersion = "4.13.0"
    const val shimmerVersion = "0.5.0"
    const val roomVersion = "2.4.2"

    const val junitVersion = "5.8.2"
    const val extJunitVersion = "1.1.3"
    const val espressoVersion = "3.4.0"
    const val mockitoVersion = "4.0.0"
}